# -------------------------------------------
#            Duels Config
# -------------------------------------------
  
#database
database:
  url: ''
  username: ''
  password: ''

#lobby spwanlocation
lobbyworldname: lobby
spawnloc:
  x: 5.5
  y: 11
  z: -15.5
  yaw: 180

firstarenacenter: 
    x: 100
    y: 10
    z: 125
    yaw: 0

duels1v1:
  gamesavailable: 30

duels2v2:
  gamesavailable: 7

duels4v4:
  gamesavailable: 2
  
kits:
  classic:
    menuitem: ''
    items:
#      itemName: amount