name: Duels
main: com.allu.duels.Duels
api-version: 1.14
version: 0.7
commands:
    duel:
      description: main command
      usage: /<command>
      aliases: [d]
    spectate:
      description: command to spectate players
      usage: /<command>
      aliases: [sp]
      permission: duels.spectate
      permission-message: Sinulla ei ole oikeuksia tuohon!
    lobby:
      description: return to lobby
      usage: /<command>
      aliases: []
      